server:
  port: 8086


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_university_forum
    username: root
    password: HAPPY#123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: online-university-forum
  

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka