server:
  port: 8090

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      routes:
        - id: ONLINE-UNIVERSITY-AUTH
          uri: lb://ONLINE-UNIVERSITY-AUTH
          predicates:
            - Path=/auth/**

        - id: ONLINE-UNIVERSITY-BACKEND
          uri: lb://ONLINE-UNIVERSITY-BACKEND
          predicates:
            - Path=/student/**,/teacher/**,/course/**,/test/**

       




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


